apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kured
  namespace: kube-system
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: kured
      version: '5.3.1'
      sourceRef:
        kind: HelmRepository
        name: kured-repo
      interval: 5m
  releaseName: kured
  values:
    fullnameOverride: kured
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: DaemonSet
              name: kured
              namespace: kube-system
            patch: |-
              apiVersion: apps/v1
              kind: DaemonSet
              metadata:
                name: kured
                namespace: kube-system
              spec:
                template:
                  spec:
                    containers:
                    - name: leader-election-sidecar
                      image: harryvinod/kured-helper:v3
                      imagePullPolicy: Always
                      securityContext:
                        runAsNonRoot: true
                        runAsUser: 65535
                      env:
                      - name: NODE_ID
                        valueFrom:
                          fieldRef:
                            fieldPath: spec.nodeName
                      - name: cluster-service
                        value: some_value
