apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kured
  namespace: kube-system
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: kured
      version: '5.4.5'
      sourceRef:
        kind: HelmRepository
        name: kured-repo
      interval: 5m
  releaseName: kured-1
  values:
    fullnameOverride: kured-2