apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kured
  namespace: kube-system
spec:
  releaseName: kured
  chart:
    spec:
      sourceRef:
        kind: GitRepository
        name: kured-repo
      path: kured
      ref: main
  values:
    fullnameOverride: kured
